---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-component-scaling

resources:
  - namespace.yaml
  - release.yaml

configMapGenerator:
  - name: aws-node-termination-handler
    files:
      - values.yaml=values/aws-node-termination-handler.yaml

generatorOptions:
  disableNameSuffixHash: true
