---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - release.yaml

configMapGenerator:
  - name: sealed-secrets-values
    namespace: flux-system
    files:
      - values.yaml=values/sealed-secrets.yaml
