---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-component-ingress

resources:
  - namespace.yaml
  - release.yaml

configMapGenerator:
  - name: ingress-nginx-values
    files:
      - values.yaml=values/ingress-nginx.yaml

generatorOptions:
  disableNameSuffixHash: true
