apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: "."
      version: '0.2.0'
      sourceRef:
        kind: GitRepository
        name: covergo-poc-helmchart
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: kube-prometheus-stack-values
    - kind: ConfigMap
      name: loki-values
    - kind: ConfigMap
      name: prometheus-blackbox-exporter-values
    - kind: ConfigMap
      name: promtail-values
    - kind: ConfigMap
      name: tempo-values
