---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: k8s-component-certs

resources:
  - namespace.yaml
  - release.yaml

configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=values/cert-manager.yaml

generatorOptions:
  disableNameSuffixHash: true
